local C = KkthnxUI[2]

local DISABLE = DISABLE

-- Actionbar
C["ActionBar"] = {
	Enable = true,
	Hotkeys = true,
	Macro = true,
	Grid = true,
	Cooldown = true,
	MmssTH = 60,
	TenthTH = 3,
	OverrideWA = false,
	MicroMenu = true,
	FadeMicroMenu = false,
	ShowStance = true,
	EquipColor = false,
	KeyDown = true,
	ButtonLock = true,
	VehButtonSize = 34,

	Bar1 = true,
	Bar1Flyout = 1,
	Bar1Size = 38,
	Bar1Font = 12,
	Bar1Num = 12,
	Bar1PerRow = 12,
	Bar1Fade = false,

	Bar2 = true,
	Bar2Flyout = 1,
	Bar2Size = 38,
	Bar2Font = 12,
	Bar2Num = 12,
	Bar2PerRow = 12,
	Bar2Fade = false,

	Bar3 = true,
	Bar3Flyout = 1,
	Bar3Size = 38,
	Bar3Font = 12,
	Bar3Num = 12,
	Bar3PerRow = 12,
	Bar3Fade = false,

	Bar4 = true,
	Bar4Flyout = 3,
	Bar4Size = 38,
	Bar4Font = 12,
	Bar4Num = 12,
	Bar4PerRow = 1,
	Bar4Fade = true,

	Bar5 = true,
	Bar5Flyout = 3,
	Bar5Size = 38,
	Bar5Font = 12,
	Bar5Num = 12,
	Bar5PerRow = 1,
	Bar5Fade = false,

	BarPetSize = 28,
	BarPetFont = 12,
	BarPetPerRow = 10,
	BarPetFade = false,

	BarStanceSize = 30,
	BarStanceFont = 12,
	BarStancePerRow = 10,
	BarStanceFade = false,

	Bar6 = false,
	Bar6Flyout = 1,
	Bar6Size = 34,
	Bar6Font = 12,
	Bar6Num = 12,
	Bar6PerRow = 12,
	Bar6Fade = false,

	Bar7 = false,
	Bar7Flyout = 1,
	Bar7Size = 34,
	Bar7Font = 12,
	Bar7Num = 12,
	Bar7PerRow = 12,
	Bar7Fade = false,

	Bar8 = false,
	Bar8Flyout = 1,
	Bar8Size = 34,
	Bar8Font = 12,
	Bar8Num = 12,
	Bar8PerRow = 12,
	Bar8Fade = false,

	BarFadeGlobal = true,
	BarFadeAlpha = 0.1,
	BarFadeDelay = 0,
	BarFadeCombat = true,
	BarFadeTarget = true,
	BarFadeCasting = true,
	BarFadeHealth = true,
	BarFadeVehicle = true,
}

-- Announcements
C["Announcements"] = {
	AlertInChat = false,
	AlertInWild = false,
	KeystoneAlert = false,
	BrokenAlert = false,
	DispellAlert = false,
	HealthAlert = false,
	InstAlertOnly = true,
	InterruptAlert = false,
	ItemAlert = false,
	KillingBlow = false,
	OnlyCompleteRing = false,
	OwnDispell = true,
	OwnInterrupt = true,
	PullCountdown = true,
	PvPEmote = false,
	QuestNotifier = false,
	QuestProgress = false,
	RareAlert = false,
	ResetInstance = true,
	SaySapped = false,
	AlertChannel = 2,
	QuestProgressEveryNth = 1,
	AnnounceWorldQuests = false,
}

-- Automation
C["Automation"] = {
	AutoKeystone = false,
	-- AutoCollapse = false,
	AutoDeclineDuels = false,
	AutoDeclinePetDuels = false,
	AutoGoodbye = false,
	AutoInvite = false,
	AutoPartySync = false,
	AutoQuest = false,
	AutoRelease = false,
	AutoResurrect = false,
	AutoResurrectThank = false,
	AutoReward = false,
	AutoScreenshot = false,
	AutoSetRole = false,
	ConfirmCinematicSkip = false,
	AutoSummon = false,
	NoBadBuffs = false,
	WhisperInvite = "inv+",
	WhisperInviteRestriction = true, -- Testing
}

C["Inventory"] = {
	AutoSell = true,
	BagBar = true,
	BagBarMouseover = false,
	BagBarSize = 32,
	BagsBindOnEquip = false,
	BagsItemLevel = false,
	BagsPerRow = 6,
	BagsWidth = 10,
	BankPerRow = 10,
	BankWidth = 12,
	DeleteButton = true,
	Enable = true,
	FilterAOE = true,
	FilterAnima = true,
	FilterAzerite = false,
	FilterCollection = true,
	FilterConsumable = true,
	FilterCustom = true,
	FilterEquipSet = false,
	FilterEquipment = true,
	FilterGoods = false,
	FilterJunk = true,
	FilterLegendary = true,
	FilterLower = true,
	FilterLegacy = false,
	FilterQuest = true,
	FilterStone = true,
	GatherEmpty = false,
	IconSize = 36,
	ItemFilter = true,
	JustBackpack = false,
	PetTrash = true,
	ReverseSort = false,
	ShowNewItem = true,
	SpecialBagsColor = false,
	UpgradeIcon = true,
	iLvlToShow = 1,
	GrowthDirection = 1,
	SortDirection = 2,
	AutoRepair = 2,
	ColorUnusableItems = true,
}

-- Buffs & Debuffs
C["Auras"] = {
	BuffSize = 32,
	BuffsPerRow = 16,
	DebuffSize = 34,
	DebuffsPerRow = 16,
	Enable = true,
	HideBlizBuff = false,
	Reminder = false,
	ReverseBuffs = false,
	ReverseDebuffs = false,
	TotemSize = 32,
	Totems = true,
	VerticalTotems = false,
}

-- Chat
C["Chat"] = {
	Background = true,
	ChatItemLevel = true,
	ChatMenu = true,
	ConfigButton = true,
	CopyButton = true,
	Emojis = false,
	Enable = true,
	Fading = true,
	FadingTimeVisible = 100,
	Freedom = true,
	Height = 170,
	Lock = true,
	LogMax = 0,
	OldChatNames = false,
	RollButton = true,
	Sticky = false,
	WhisperColor = true,
	Width = 400,
	TimestampFormat = 1,
}

-- Datatext
C["DataText"] = {
	Coords = false,
	Friends = false,
	Gold = false,
	Guild = false,
	GuildSortBy = 1,
	GuildSortOrder = true,
	HideText = false,
	IconColor = { 102 / 255, 157 / 255, 255 / 255 },
	Latency = true,
	Location = true,
	Spec = false,
	System = true,
	Time = true,
}

C["AuraWatch"] = {
	Enable = true,
	ClickThrough = false,
	IconScale = 1,
	DeprecatedAuras = false,
}

-- General
C["General"] = {
	AutoScale = true,
	ColorTextures = false,
	MinimapIcon = false,
	MissingTalentAlert = true,
	MoveBlizzardFrames = false,
	NoErrorFrame = false,
	NoTutorialButtons = false,
	TexturesColor = { 1, 1, 1 },
	UIScale = 0.71,
	UseGlobal = false,
	Texture = "KkthnxUI",
	SmoothAmount = 0.25,
	BorderStyle = "KkthnxUI",
	NumberPrefixStyle = 1,
	GlowMode = 3,
	VersionCheck = true,
}

-- Loot
C["Loot"] = {
	AutoConfirm = false,
	AutoGreed = false,
	Enable = true,
	FastLoot = false,
	GroupLoot = true,
}

-- Minimap
C["Minimap"] = {
	Calendar = true,
	EasyVolume = false,
	Enable = true,
	MailPulse = true,
	QueueStatusText = false,
	ShowRecycleBin = true,
	Size = 210,
	RecycleBinPosition = 1,
	LocationText = 3,
}

-- Miscellaneous
C["Misc"] = {
	RaidTool = true,
	RMRune = false,
	DBMCount = "10",
	MarkerBarSize = 22,
	AFKCamera = false,
	AutoBubbles = false,
	ColorPicker = false,
	EnhancedFriends = false,
	EnhancedMail = false,
	ExpRep = true,
	GemEnchantInfo = false,
	HideBanner = false,
	HideBossEmote = false,
	ImprovedStats = false,
	ItemLevel = false,
	MDGuildBest = false,
	MaxCameraZoom = 2.6,
	MuteSounds = true,
	NoTalkingHead = false,
	QuestTool = false,
	QueueTimers = false,
	QueueTimerAudio = true,
	QueueTimerWarning = true,
	QueueTimerHideOtherTimers = true,
	QuickJoin = false,
	QuickMenuList = true,
	ShowWowHeadLinks = false,
	SlotDurability = false,
	TradeTabs = false,
	EasyMarking = false,
	YClassColors = true,
	EasyMarkKey = 1,
	ShowMarkerBar = 4,
}

C["Nameplate"] = {
	ColorByDot = false, -- This is not ready
	DotColor = { 1, 0.5, 0.2 },
	DotSpellList = {
		Spells = {},
	},
	AKSProgress = false,
	AuraSize = 28,
	CastTarget = false,
	CastbarGlow = true,
	ClassIcon = false,
	ColoredTarget = true,
	CustomColor = { 0, 0.8, 0.3 },
	CustomUnitColor = true,
	CustomUnitList = "",
	DPSRevertThreat = false,
	-- Distance = 42,
	Enable = true,
	ExecuteRatio = 0,
	FriendPlate = false,
	FriendlyCC = false,
	FullHealth = false,
	HealthTextSize = 13,
	HostileCC = true,
	InsecureColor = { 1, 0, 0 },
	InsideView = true,
	MaxAuras = 5,
	MinAlpha = 0.6,
	MinScale = 1,
	CVarOnlyNames = false,
	CVarShowNPCs = false,
	NameOnly = true,
	NameTextSize = 13,
	NameplateClassPower = true,
	OffTankColor = { 0.2, 0.7, 0.5 },
	PPGCDTicker = true,
	PPPowerText = true,
	HarmWidth = 200,
	HarmHeight = 62,
	EnemyThru = false,
	FriendlyThru = false,
	HelpWidth = 200,
	HelpHeight = 62,
	PPHeight = 10,
	PPHideOOC = true,
	PPIconSize = 32,
	PPOnFire = false,
	PPPHeight = 8,
	PlateAuras = true,
	PlateHeight = 18,
	PlateWidth = 200,
	PowerUnitList = "",
	QuestIndicator = true,
	SecureColor = { 1, 0, 1 },
	SelectedScale = 1.1,
	ShowPlayerPlate = false,
	Smooth = false,
	TankMode = false,
	TargetColor = { 0, 0.6, 1 },
	TargetIndicatorColor = { 1, 1, 0 },
	TransColor = { 1, 0.8, 0 },
	VerticalSpacing = 0.7,
	AuraFilter = 3,
	TargetIndicator = 4,
	TargetIndicatorTexture = "Interface\\Addons\\KkthnxUI\\Media\\Nameplates\\NeonBlueArrow",
}

-- Skins
C["Skins"] = {
	Bartender4 = false,
	BigWigs = false,
	BlizzardFrames = true,
	ButtonForge = false,
	ChatBubbleAlpha = 0.9,
	ChatBubbles = true,
	ChocolateBar = false,
	DeadlyBossMods = false,
	Details = false,
	Dominos = false,
	Hekili = false,
	RareScanner = false,
	Skada = false,
	Spy = false,
	TalkingHeadBackdrop = true,
	TellMeWhen = false,
	TitanPanel = false,
	WeakAuras = false,
	ObjectiveFontSize = 12,
	QuestFontSize = 11,
}

-- Tooltip
C["Tooltip"] = {
	ClassColor = false,
	CombatHide = false,
	Cursor = false,
	Enable = true,
	FactionIcon = false,
	HideJunkGuild = true,
	HideRank = true,
	HideRealm = true,
	HideTitle = true,
	Icons = true,
	LFDRole = false,
	MDScore = true,
	ShowIDs = false,
	ShowMount = false,
	SpecLevelByShift = true,
	TargetBy = true,
	CursorMode = 1,
	TipAnchor = 4,
}

-- Unitframe
C["Unitframe"] = {
	AdditionalPower = false,
	AllTextScale = 1, -- Testing
	AutoAttack = true,
	CastClassColor = false,
	CastReactionColor = false,
	CastbarLatency = true,
	ClassResources = true,
	CombatFade = false,
	CombatText = false,
	DebuffHighlight = true,
	Enable = true,
	FCTOverHealing = false,
	GlobalCooldown = true,
	HotsDots = true,
	OnlyShowPlayerDebuff = false,
	Range = true,

	-- Player
	PlayerBuffs = false,
	PlayerBuffsPerRow = 6,
	PlayerCastbar = true,
	PlayerCastbarHeight = 28,
	PlayerCastbarIcon = true,
	PlayerCastbarWidth = 268,
	PlayerDebuffs = false,
	PlayerDebuffsPerRow = 7,
	PlayerHealthHeight = 34,
	PlayerHealthWidth = 200,
	PlayerPowerHeight = 16,

	PvPIndicator = true,
	ResurrectSound = false,
	ShowHealPrediction = true,
	ShowPlayerLevel = true,
	HideMaxPlayerLevel = false,
	Smooth = false,
	Stagger = true,

	SwingBar = false,
	SwingWidth = 274,
	SwingHeight = 14,
	SwingTimer = true,
	OffOnTop = false,

	-- Target
	TargetHealthHeight = 34,
	TargetHealthWidth = 200,
	TargetPowerHeight = 16,
	TargetBuffs = true,
	TargetBuffsPerRow = 7,
	TargetCastbar = true,
	TargetCastbarIcon = true,
	TargetCastbarHeight = 34,
	TargetCastbarWidth = 268,
	TargetDebuffs = true,
	TargetDebuffsPerRow = 6,

	-- Focus
	FocusBuffs = true,
	FocusCastbar = true,
	FocusCastbarHeight = 24,
	FocusCastbarIcon = true,
	FocusCastbarWidth = 208,
	FocusDebuffs = true,
	FocusHealthHeight = 32,
	FocusHealthWidth = 180,
	FocusPowerHeight = 14,

	-- TargetOfTarget
	TargetTargetHealthHeight = 18,
	TargetTargetHealthWidth = 100,
	TargetTargetPowerHeight = 10,
	HideTargetOfTargetLevel = false,
	HideTargetOfTargetName = false,
	HideTargetofTarget = false,

	-- Pet
	PetHealthHeight = 18,
	PetHealthWidth = 100,
	PetPowerHeight = 10,
	HidePetLevel = false,
	HidePetName = false,
	HidePet = false,

	-- FocusTarget
	FocusTargetHealthHeight = 18,
	FocusTargetHealthWidth = 100,
	FocusTargetPowerHeight = 10,
	HideFocusTargetLevel = false,
	HideFocusTargetName = false,
	HideFocusTarget = false,
	HealthbarColor = 1,
	PortraitStyle = 1,
}

C["Party"] = {
	CastbarIcon = false,
	Castbars = false,
	Enable = true,
	HealthHeight = 22,
	HealthWidth = 150,
	PortraitTimers = false,
	PowerHeight = 12,
	ShowBuffs = false,
	ShowHealPrediction = true,
	ShowPartySolo = false,
	ShowPet = false,
	ShowPlayer = true,
	Smooth = false,
	TargetHighlight = false,
	HealthbarColor = 1,
}

-- SimpleParty (Raid-style compact party frames)
C["SimpleParty"] = {
	Enable = false,
	HealthbarColor = 1,
	HealthHeight = 44,
	HealthWidth = 70,
	HorizonParty = false,
	ManabarShow = false,
	PowerBarShow = false,
	PowerBarHeight = 5,
	RaidBuffsStyle = 2,
	ShowHealPrediction = true,
	Smooth = false,
	TargetHighlight = false,
}

C["Boss"] = {
	CastbarIcon = true,
	Castbars = true,
	Enable = true,
	Smooth = false,
	HealthHeight = 24,
	HealthWidth = 150,
	PowerHeight = 12,
	YOffset = 54,
	HealthbarColor = 1,
}

C["Arena"] = {
	CastbarIcon = true,
	Castbars = true,
	Enable = true,
	Smooth = false,
	HealthHeight = 20,
	HealthWidth = 134,
	PowerHeight = 10,
	YOffset = 54,
	HealthbarColor = 1,
}

-- Raidframe
C["Raid"] = {
	DebuffWatch = true,
	DebuffWatchDefault = true,
	DesaturateBuffs = false,
	Enable = true,
	Height = 44,
	HorizonRaid = false,
	MainTankFrames = true,
	PowerBarShow = false,
	ManabarShow = false,
	NumGroups = 6,
	RaidUtility = true,
	ReverseRaid = false,
	ShowHealPrediction = true,
	ShowNotHereTimer = true,
	ShowRaidSolo = false,
	ShowTeamIndex = false,
	Smooth = false,
	TargetHighlight = false,
	Width = 70,
	RaidBuffsStyle = 2,
	RaidBuffs = 1,
	AuraTrack = true,
	AuraTrackIcons = true,
	AuraTrackSpellTextures = true,
	AuraTrackThickness = 5,
	HealthbarColor = 1,
	HealthFormat = 1,
	UseRaidForParty = false,
}

-- Worldmap
C["WorldMap"] = {
	AlphaWhenMoving = 0.35,
	Coordinates = true,
	FadeWhenMoving = true,
	MapRevealGlow = true,
	SmallWorldMap = true,
}
