local K, C = unpack(KkthnxUI)
local Module = K:GetModule("Blizzard")

local _G = _G

local bitfieldListing = {
	_G.LE_FRAME_TUTORIAL_ACCCOUNT_CLUB_FINDER_NEW_FEATURE,
	_G.LE_FRAME_TUTORIAL_ACCCOUNT_RAF_INTRO,
	_G.LE_FRAME_TUTORIAL_ACCOUNT_CLUB_FINDER_NEW_COMMUNITY_JOINED,
	_G.LE_FRAME_TUTORIAL_ARTIFACT_APPEARANCE_TAB,
	_G.LE_FRAME_TUTORIAL_ARTIFACT_RELIC_MATCH,
	_G.LE_FRAME_TUTORIAL_AZERITE_FIRST_POWER_LOCKED_IN,
	_G.LE_FRAME_TUTORIAL_AZERITE_ITEM_IN_BAG,
	_G.LE_FRAME_TUTORIAL_AZERITE_ITEM_IN_SLOT,
	_G.LE_FRAME_TUTORIAL_AZERITE_RESPEC,
	_G.LE_FRAME_TUTORIAL_BONUS_ROLL_ENCOUNTER_JOURNAL_LINK,
	_G.LE_FRAME_TUTORIAL_BOOSTED_SPELL_BOOK,
	_G.LE_FRAME_TUTORIAL_BOUNTY_FINISHED,
	_G.LE_FRAME_TUTORIAL_BOUNTY_INTRO,
	_G.LE_FRAME_TUTORIAL_BRAWL,
	_G.LE_FRAME_TUTORIAL_CHAT_CHANNELS,
	_G.LE_FRAME_TUTORIAL_CLUB_FINDER_LINKING,
	_G.LE_FRAME_TUTORIAL_CLUB_FINDER_LINKING,
	_G.LE_FRAME_TUTORIAL_CLUB_FINDER_NEW_APPLICANTS_GUILD_LEADER,
	_G.LE_FRAME_TUTORIAL_CLUB_FINDER_NEW_COMMUNITY_LEADER,
	_G.LE_FRAME_TUTORIAL_CLUB_FINDER_NEW_GUILD_LEADER,
	_G.LE_FRAME_TUTORIAL_CORRUPTION_CLEANSER,
	_G.LE_FRAME_TUTORIAL_FRIENDS_LIST_QUICK_JOIN,
	_G.LE_FRAME_TUTORIAL_GAME_TIME_AUCTION_HOUSE,
	_G.LE_FRAME_TUTORIAL_GARRISON_BUILDING,
	_G.LE_FRAME_TUTORIAL_GARRISON_LANDING,
	_G.LE_FRAME_TUTORIAL_GARRISON_ZONE_ABILITY,
	_G.LE_FRAME_TUTORIAL_HEIRLOOM_JOURNAL,
	_G.LE_FRAME_TUTORIAL_HEIRLOOM_JOURNAL_LEVEL,
	_G.LE_FRAME_TUTORIAL_HEIRLOOM_JOURNAL_TAB,
	_G.LE_FRAME_TUTORIAL_INVENTORY_FIXUP_CHECK_EXPANSION_LEGION,
	_G.LE_FRAME_TUTORIAL_INVENTORY_FIXUP_EXPANSION_LEGION,
	_G.LE_FRAME_TUTORIAL_ISLANDS_QUEUE_BUTTON,
	_G.LE_FRAME_TUTORIAL_ISLANDS_QUEUE_INFO_FRAME,
	_G.LE_FRAME_TUTORIAL_LFG_LIST,
	_G.LE_FRAME_TUTORIAL_MOUNT_EQUIPMENT_SLOT_FRAME,
	_G.LE_FRAME_TUTORIAL_PET_JOURNAL,
	_G.LE_FRAME_TUTORIAL_PROFESSIONS,
	_G.LE_FRAME_TUTORIAL_PVP_SPECIAL_EVENT,
	_G.LE_FRAME_TUTORIAL_PVP_TALENTS_FIRST_UNLOCK,
	_G.LE_FRAME_TUTORIAL_PVP_WARMODE_UNLOCK,
	_G.LE_FRAME_TUTORIAL_QUEST_SESSION,
	_G.LE_FRAME_TUTORIAL_REAGENT_BANK_UNLOCK,
	_G.LE_FRAME_TUTORIAL_REPUTATION_EXALTED_PLUS,
	_G.LE_FRAME_TUTORIAL_SPEC,
	_G.LE_FRAME_TUTORIAL_SPELLBOOK,
	_G.LE_FRAME_TUTORIAL_TALENT,
	_G.LE_FRAME_TUTORIAL_TOYBOX,
	_G.LE_FRAME_TUTORIAL_TOYBOX_FAVORITE,
	_G.LE_FRAME_TUTORIAL_TOYBOX_MOUSEWHEEL_PAGING,
	_G.LE_FRAME_TUTORIAL_TRADESKILL_RANK_STAR,
	_G.LE_FRAME_TUTORIAL_TRADESKILL_UNLEARNED_TAB,
	_G.LE_FRAME_TUTORIAL_TRANSMOG_JOURNAL_TAB,
	_G.LE_FRAME_TUTORIAL_TRANSMOG_MODEL_CLICK,
	_G.LE_FRAME_TUTORIAL_TRANSMOG_MODEL_CLICK,
	_G.LE_FRAME_TUTORIAL_TRANSMOG_OUTFIT_DROPDOWN,
	_G.LE_FRAME_TUTORIAL_TRANSMOG_SETS_TAB,
	_G.LE_FRAME_TUTORIAL_TRANSMOG_SETS_VENDOR_TAB,
	_G.LE_FRAME_TUTORIAL_TRANSMOG_SPECS_BUTTON,
	_G.LE_FRAME_TUTORIAL_TRIAL_BANKED_XP,
	_G.LE_FRAME_TUTORIAL_WARFRONT_CONSTRUCTION,
	_G.LE_FRAME_TUTORIAL_WARFRONT_RESOURCES,
	_G.LE_FRAME_TUTORIAL_WORLD_MAP_FRAME,
	_G.LE_FRAME_TUTORIAL_WORLD_MAP_THREAT_ICON,
}

function Module:SetupKillTutorials(addon)
	if addon == "Blizzard_Collections" then
		if PetJournalTutorialButton then
			PetJournalTutorialButton:Kill()
		end
	end

	if addon == "Blizzard_TalentUI" then
		if PlayerTalentFrameSpecializationTutorialButton then
			PlayerTalentFrameSpecializationTutorialButton:Kill()
		end
	end

	K:UnregisterEvent("ADDON_LOADED", Module.SetupKillTutorials)

	if WorldMapFrame.BorderFrame.Tutorial then
		WorldMapFrame.BorderFrame.Tutorial:Kill()
	end

	if SpellBookFrameTutorialButton then
		SpellBookFrameTutorialButton:Kill()
	end
end

function Module:CreateDisableTutorials()
	if not C["General"].NoTutorialButtons then
		return
	end

	K:RegisterEvent("ADDON_LOADED", Module.SetupKillTutorials)

	for _, v in ipairs(bitfieldListing) do
		if v then
			SetCVarBitfield("closedInfoFrames", v, true)
		end
		SetCVar("showTutorials", 0)
	end
end
