local K, C, L = unpack(select(2, ...))

-- -- Wow API
-- local collectgarbage = collectgarbage
-- local InCombatLockdown = InCombatLockdown
-- local UnitIsAFK = UnitIsAFK
--
-- local Events = 0
-- local CollectGarbage = CreateFrame("Frame")
-- CollectGarbage:RegisterEvent("PLAYER_ENTERING_WORLD")
-- CollectGarbage:RegisterEvent("PLAYER_FLAGS_CHANGED")
-- CollectGarbage:SetScript("OnEvent", function(self, event, unit)
-- 	Events = Events + 1
--
-- 	if (InCombatLockdown() and Events > 25000) or (not InCombatLockdown() and Events > 10000) or (event == "PLAYER_ENTERING_WORLD") then
-- 		collectgarbage("collect")
-- 		Events = 0
--
-- 		self:UnregisterEvent("PLAYER_ENTERING_WORLD")
-- 	else
-- 		if (unit ~= "player") then
-- 			return
-- 		end
--
-- 		if UnitIsAFK(unit) then
-- 			collectgarbage("collect")
-- 		end
-- 	end
-- end)